# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myUi.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(517, 449)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_3.addWidget(self.checkBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.plainTextEdit_source = QtWidgets.QPlainTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit_source.setFont(font)
        self.plainTextEdit_source.setObjectName("plainTextEdit_source")
        self.verticalLayout.addWidget(self.plainTextEdit_source)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.doubleSpinBox.setFont(font)
        self.doubleSpinBox.setAutoFillBackground(False)
        self.doubleSpinBox.setSingleStep(0.1)
        self.doubleSpinBox.setProperty("value", 0.1)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout.addWidget(self.doubleSpinBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.radioButton_csv = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_csv.setFont(font)
        self.radioButton_csv.setObjectName("radioButton_csv")
        self.horizontalLayout_2.addWidget(self.radioButton_csv)
        self.radioButton_tab = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_tab.setFont(font)
        self.radioButton_tab.setObjectName("radioButton_tab")
        self.horizontalLayout_2.addWidget(self.radioButton_tab)
        self.radioButton_other = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_other.setObjectName("radioButton_other")
        self.horizontalLayout_2.addWidget(self.radioButton_other)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setText("")
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.pushButton_run = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_run.setFont(font)
        self.pushButton_run.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_run.setObjectName("pushButton_run")
        self.horizontalLayout_4.addWidget(self.pushButton_run)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.pushButton_pause = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_pause.setFont(font)
        self.pushButton_pause.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_pause.setObjectName("pushButton_pause")
        self.horizontalLayout_4.addWidget(self.pushButton_pause)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.pushButton_abort = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_abort.setFont(font)
        self.pushButton_abort.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_abort.setObjectName("pushButton_abort")
        self.horizontalLayout_4.addWidget(self.pushButton_abort)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 517, 22))
        self.menubar.setObjectName("menubar")
        self.menu_About = QtWidgets.QMenu(self.menubar)
        self.menu_About.setObjectName("menu_About")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionabout_Author = QtWidgets.QAction(MainWindow)
        self.actionabout_Author.setObjectName("actionabout_Author")
        self.actionVersion_1_0 = QtWidgets.QAction(MainWindow)
        self.actionVersion_1_0.setObjectName("actionVersion_1_0")
        self.menu_About.addAction(self.actionabout_Author)
        self.menu_About.addSeparator()
        self.menu_About.addAction(self.actionVersion_1_0)
        self.menubar.addAction(self.menu_About.menuAction())

        self.retranslateUi(MainWindow)
        self.pushButton_abort.clicked.connect(self.progressBar.close)
        self.radioButton_other.toggled['bool'].connect(self.lineEdit.setEnabled)
        self.pushButton_run.clicked.connect(self.progressBar.show)
        self.checkBox.clicked['bool'].connect(MainWindow.test)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AutoMotion"))
        self.checkBox.setText(_translate("MainWindow", "Keep On Top"))
        self.plainTextEdit_source.setPlainText(_translate("MainWindow", "Hello!"))
        self.label.setText(_translate("MainWindow", "Interval(ms)"))
        self.label_2.setText(_translate("MainWindow", "Source form (Separator) :"))
        self.radioButton_csv.setText(_translate("MainWindow", ".csv"))
        self.radioButton_tab.setText(_translate("MainWindow", "Tab"))
        self.radioButton_other.setText(_translate("MainWindow", "Specify Myself"))
        self.pushButton_run.setText(_translate("MainWindow", "Let\'s Go"))
        self.pushButton_pause.setText(_translate("MainWindow", "Pause"))
        self.pushButton_abort.setText(_translate("MainWindow", "Abort"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.menu_About.setTitle(_translate("MainWindow", "&About"))
        self.actionabout_Author.setText(_translate("MainWindow", "about Author"))
        self.actionVersion_1_0.setText(_translate("MainWindow", "Version 1.0"))
